### ==========================================
### ১. ইউজার রেজিস্টার (নতুন আইডি ও অ্যাকাউন্ট তৈরি)
### ==========================================
POST https://ecommerce-api-9wc9.onrender.com/api/auth/register
Content-Type: application/json

{
    "name": "Jihad Khan",
    "email": "jihad@gmail.com",
    "password": "123456",
    "role": "seller"
}


### ==========================================
### ২. ইউজার লগইন (সঠিক ২৪ অক্ষরের টোকেন পাওয়ার জন্য)
### ==========================================
# ওপরে রেজিস্টার করার পর এই লগইন রিকোয়েস্টে হিট করবেন।
# নিচে রেসপন্সে যে নতুন token পাবেন, সেটি কপি করে ৩ ও ৪ নম্বর রিকোয়েস্টে বসাবেন।
POST https://ecommerce-api-9wc9.onrender.com/api/auth/login
Content-Type: application/json

{
    "email": "jihad@gmail.com",
    "password": "123456"
}


### ==========================================
### ৩. কার্টে প্রোডাক্ট যোগ করা
### ==========================================
# ২ নম্বর থেকে পাওয়া নতুন টোকেনটি "Bearer " এর পর বসিয়ে দিন
POST https://ecommerce-api-9wc9.onrender.com/api/orders/cart/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTkzNTkyZjAxZmRkMTE3YzE3YmZhZCIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3ODQyMzEzMjUsImV4cCI6MTc4NDMxNzcyNX0.iCV3sBgt_-ndersqowH1rwCfe0CUuk795lvGKEi7R20
Content-Type: application/json

{
    "productId": "6a5926dbae2b42b19368f9d6",
    "quantity": 1
}


### ==========================================
### ৪. ইউজারের কার্ট দেখা
### ==========================================
# ২ নম্বর থেকে পাওয়া নতুন টোকেনটি "Bearer " এর পর বসিয়ে দিন
GET https://ecommerce-api-9wc9.onrender.com/api/orders/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3ODQyMjYzODY0NDgiLCJyb2xlIjoic2VsbGVyIiwiaWF0IjoxNzg0MjI2NDk3LCJleHAiOjE3ODQzMTI4OTd9.KX2tj8xZBIpDvby_IgmFc4vEJ9iBtgw9eQj_WW0q9y8


### ==========================================
### ৫. সব প্রোডাক্ট দেখা (সবাই দেখতে পারবে)
### ==========================================
GET https://ecommerce-api-9wc9.onrender.com/api/seller/all-products


### ==========================================
### ৬. কার্ট থেকে অর্ডার প্লেস করা (Checkout)
### ==========================================
POST https://ecommerce-api-9wc9.onrender.com/api/orders/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTkzNTkyZjAxZmRkMTE3YzE3YmZhZCIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3ODQyMzE5MDAsImV4cCI6MTc4NDMxODMwMH0.gjd52TmgTDbxycovri6n9OODsf5NSmOb1kRBqhltwh8
Content-Type: application/json

{
    "shippingAddress": "House 12, Road 5, Dhanmondi, Dhaka"
}


### ==========================================
### ৭. পেমেন্ট ইনিশিয়েট করা (SSLCommerz Gateway URL জেনারেট করা)
### ==========================================
POST https://ecommerce-api-9wc9.onrender.com/api/payment/initiate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTkzNTkyZjAxZmRkMTE3YzE3YmZhZCIsInJvbGUiOiJzZWxsZXIiLCJpYXQiOjE3ODQyMzE5MDAsImV4cCI6MTc4NDMxODMwMH0.gjd52TmgTDbxycovri6n9OODsf5NSmOb1kRBqhltwh8
Content-Type: application/json

{
    "orderId": "6a59f7d60014e1d77625f8cd"
}